name = input("who are you")
city = input("where do you live")
age = input("how old you are")
hobby = ("what is your hobby")
movie = input("what is your is your fevorite movie")
food = input("what is your fevorite food")

print("----your detailed filled by you----")
print("Name", name)
print("City",city)
print("Age",age)
print("Hobby",hobby)
print("Movie", movie)
print("Food", food)
print("----The End ----")